[files.assets.config]
target_dir="src/zimscraperlib/rewriting/statics"
execute_after=[
    "cd ../../../../ && python rules/generate_rules.py", # generate Python (and JS) rules
]

[files.assets.actions."wombat.js"]
action="get_file"
source="https://cdn.jsdelivr.net/npm/@webrecorder/wombat@3.8.7/dist/wombat.js"
target_file="wombat.js"
